FROM alfg/nginx-rtmp

RUN apk add --no-cache jq bash

WORKDIR /app
COPY ./app/ .
#RUN rm -R /usr/local/nginx/html/players
RUN mkdir -p /usr/local/nginx/html
#COPY ./player.html /usr/local/nginx/html
COPY ./player.html /srv/www/
RUN rm /etc/nginx/nginx.conf
COPY ./nginx_hls.conf /etc/nginx/nginx.conf
EXPOSE 1935
CMD bash /app/entrypoint.sh